stages:
 - build
 - test
 - deploy

variables:
    TEST_DIR: /home/pi/robosoul
    OUT_DIR: /home/pi/robosoul/results
    CI_NUMBER: '2'
    CI_STRATEGY: '666'
    CI_FORESIGHT: '4'
    CI_COOLDOWN: '0.001'
    CI_HYPER: '0.005'
    
prepare_matrixes:
 stage: build
 tags:
    - robo
 only:
    - schedules
    - triggers
    - web
 script:
    - rm -rf $TEST_DIR/*
    - cd $TEST_DIR
    - mkdir -p results
    - cp $CI_PROJECT_DIR/raspberry/* .
    - ./build_initials.sh

learning:
 stage: test
 tags:
    - robo
 only:
    - schedules
    - triggers
    - web
 variables:
    GIT_STRATEGY: none
 script:
    - cd $TEST_DIR
    - ./run_test.sh

build_images:
 stage: deploy
 when: always
 tags:
    - robo
 only:
    - schedules
    - triggers
    - web
 variables:
    GIT_STRATEGY: none
 script:
    - cd $TEST_DIR
    - python3 viewer.py
    - cp $TEST_DIR/config.json $OUT_DIR | true
    - cp $TEST_DIR/*ev.xlsx $OUT_DIR | true
    - cp -r $OUT_DIR $CI_PROJECT_DIR/artifacts_$CI_PIPELINE_ID | true

 artifacts:
    when: always
    paths:
      - $CI_PROJECT_DIR/artifacts_$CI_PIPELINE_ID
    expire_in: 2 weeks
