stages:
 - build
 - pre-test
 - test
 - deploy

variables:
 TEST_DIR: $CI_PROJECT_DIR
 OUT_DIR: 'C:\\Users\\work\\Documents\\Robo-storage'
 CACHE_DIR: $CI_PROJECT_DIR\results
 CI_LOS: 'true'
 CI_NUMBER: '2'
 CI_STRATEGY: '776'
 CI_FORESIGHT: '4'
 CI_COOLDOWN: '0.001'
 CI_HYPER: '0.005'
 
.ci_config:
 tags:
    - work
 only:
    - schedules
    - triggers
    - web
 variables:
    GIT_STRATEGY: none

prepare_matrixes:
 stage: build
 extends:
    - .ci_config
 variables:
    GIT_STRATEGY: fetch
 script:
    #- rm -rf $TEST_DIR/*
    - cd $TEST_DIR
    - mkdir -p results
    - cp $CI_PROJECT_DIR/raspberry/* .
    - bash build_initials.sh

le.on storage:
 stage: pre-test
 extends:
    - .ci_config
 script:
    - cd $TEST_DIR
    - bash learn_on_storage.sh

learning:
 stage: test
 extends:
    - .ci_config
 script:
    - cd $TEST_DIR
    - bash run_test.sh
 artifacts:
    when: on_failure
    paths:
      - config.json

build_images:
 stage: deploy
 when: always
 extends:
    - .ci_config
 script:
    - cd $TEST_DIR
    - python viewer.py
    - cp $TEST_DIR/config.json $CACHE_DIR | true
    - cp $TEST_DIR/*ev.xlsx $CACHE_DIR | true
    - cp -r $CACHE_DIR $CI_PROJECT_DIR/artifacts_$CI_PIPELINE_ID | true

 artifacts:
    when: always
    paths:
      - $CI_PROJECT_DIR/artifacts_$CI_PIPELINE_ID
    expire_in: 2 weeks
