stages:
 - build
 - test

variables:
    TEST_DIR: $CI_PROJECT_DIR/raspberry

build:
 stage: build
 tags:
    - robo
 only:
    - schedules
    - triggers
    - web
 script:
    - cd $TEST_DIR
    - ./build_initials.sh

test:
 stage: test
 tags:
    - robo
 only:
    - schedules
    - triggers
    - web
 variables:
    GIT_STRATEGY: none
 script:
    - cd $TEST_DIR
    - ./run_test.sh
