stages:
 - build
 - test

build:
 stage: build
 tags:
    - robo
 only:
    - schedules
    - triggers
    - web
 script:
    - cd raspberry
    - ./build_initials.sh

test:
 stage: test
 tags:
    - robo
 only:
    - schedules
    - triggers
    - web
 script:
    - ./run_test.sh
